### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by cerkit** [CedricDumont/CExtensions-EFModelGenerator#8]
Exception Message : Exception has been thrown by the target of an invocation.
Exception Stack :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CExtensions.EFModelGenerator.Utils.CallMethodOnObject(Object obj, String method, Object[] mparams)
   at CExtensions.EFModelGenerator.ModelInitializer.LoadTables(Schema schema)
   at CExtensions.EFModelGenerator.ModelInitializer.Initialize(String schemaName)
   at CExtensions.EFModelGenerator.Generator.Generate(TextWriter writer)

Inner Exception Message : Exception has been thrown by the target of an invocation.
Inner Exception Stack :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CExtensions.EFModelGenerator.Utils.CallMethodOnObject(Object obj, String method, Object[] mparams)
   at CExtensions.EFModelGenerator.ModelInitializer.LoadTables(Schema schema)
   at CExtensions.EFModelGenerator.ModelInitializer.Initialize(String schemaName)
   at CExtensions.EFModelGenerator.Generator.Generate(TextWriter writer)

**Comment by cerkit** [comment]
I'm getting this exception with the plugin as well as using the Console application approach. I used the sample Oracle config and the Oracle libraries.
